<?php

define('MOONMARS_CHANNEL_DEFAULT_PAGE_SIZE', 10);

/**
 * Implements hook_menu().
 */
//function moonmars_channels_menu() {
//}

/**
 * Return array of node types that have channels.
 *
 * @return array
 */
function moonmars_channels_node_types() {
  return array(
    'group',
    'event',
    'project'
  );
}

/**
 * Common code for inserting or updating nodes.
 *
 * @param $node
 */
function moonmars_channels_entity_save($entity, $type) {
  // Update the channel's alias and title in case the entity's title was changed:
  $entity = mmcEntity::getEntity($type, $entity);
  if ($entity) {
    $channel = $entity->channel();
    $channel->updateAliasAndTitle();
  }
}

/**
 * Implements hook_node_insert().
 */
function moonmars_channels_entity_insert($entity, $type) {
  moonmars_channels_entity_save($entity, $type);
}

/**
 * Implements hook_node_update().
 */
function moonmars_channels_entity_update($entity, $type) {
  moonmars_channels_entity_save($entity, $type);
}

/**
 * Checks if we're on a node page with an embedded channel.
 *
 * @return bool
 */
function moonmars_channels_is_embedded_channel_page() {
  $n_args = arg_count();

  if ($n_args == 2 && is_uint(arg(1))) {
    if (arg(0) == 'user') {
      return TRUE;
    }
    elseif (arg(0) == 'node') {
      $node = node_load(arg(1));
      return in_array($node->type, moonmars_channels_node_types());
    }
  }

  return FALSE;
}

/**
 * Implements hook_form_alter().
 */
function moonmars_channels_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  switch ($form_id) {
    case 'channel_node_form':
      $channel = Channel::create($form['#node']);

      // Update the title:
      drupal_set_title("Edit links for " . $channel->parentEntityName());

      // Hide the channel title field:
      unset($form['title']);
      break;
  }
}
