<?php

/**
 * Get the number of users in a group.
 *
 * @param int $gid
 *   The group nid.
 * @return int
 *   The number of users in the group, or FALSE if $gid is invalid.
 */
function moonmars_groups_member_count($group_nid) {
  $q = db_select('view_relationship', 'vr')
    ->fields('vr', array('rid'))
    ->condition('relation_type', 'is_member_of')
    ->condition('entity_id1', $group_nid);
  $rs = $q->execute();
  return $rs->rowCount();
}

/**
 * Implements hook_menu().
 */
function moonmars_groups_menu() {
  $items = array();
//  $items['group/%'] = array(
//    'page callback'    => 'moonmars_groups_channel',
//    'page arguments'   => array(1),
//    'access callback'  => TRUE, // 'moonmars_groups_can_view',
//    'type'             => MENU_CALLBACK,
//  );
  return $items;
}

/**
 * Checks if this is a group page.
 * This function can probably be improved by using native Drupal/context variables.
 *
 * @return bool
 */
function moonmars_groups_is_group_page() {
  if (arg(0) == 'node' && is_uint(arg(1)) && arg(2) != 'edit') {
    $node = node_load(arg(1));
    return $node->type == 'group';
  }
  return FALSE;
}
