<?php

/**
 * Implements hook_init().
 */
function moonmars_init() {
  // Activate debugging:
  dbg_on();
}

/**
 * Implements hook_menu().
 */
function moonmars_menu() {
  $items = array();
  $items['home'] = array(
    'page callback' => 'moonmars_home',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 *
 * Place form changes here that belong to all forms.
 */
function moonmars_form_alter(&$form, &$form_state, $form_id) {
  // Attach the selectBox JS:
//  $form['#attached']['js'][] = '/sites/all/libraries/jquery/selectBox/jquery.selectBox.js';
}

/**
 * Redirect the user to the appropriate default start page.
 */
function moonmars_home() {
  if (user_is_logged_in()) {
    drupal_goto('profile');
  }
  else {
    drupal_goto('news');
  }
}
