<?php

/**
 * Scans a piece of text (item or comment) for @ references to members, and converts these to links.
 *
 * @param $text
 */
function moonmars_text_scan($text, $nl2br = FALSE) {
  $text2 = $text;

  // Make URLs into links:
  $scheme = "https?:\/\/";
  $domain_name = "[a-z0-9](([a-z0-9\-\.]+)?[a-z0-9])?";
  $ip_addr = "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}";
  $port_path_query_fragment = "[-A-Z0-9+&@#\/%=~_|$?!:,.]*[A-Z0-9+&@#\/%=~_|$]";
  $url_rx = "/($scheme)(($domain_name)|($ip_addr))($port_path_query_fragment)?/i";
  $text2 = preg_replace($url_rx, "<a href='$0' target='_blank'>$0</a>", $text2);
//  $n_matches = preg_match_all($url_rx, $text2, $matches);
//  dbg($matches);

////  dbg($text2);
//  $n_urls = preg_match_all($url_rx, $text2, $matches);
//  if ($n_urls) {
//    foreach ($matches[0] as $n => $url) {
//      $scheme = $matches[1][$n];
//      if ($scheme) {
//        $text2 = str_replace($url, "<a href='$url' target='_blank'>$url</a>", $text2);
//      }
//      else {
//        $text2 = str_replace($url, "<a href='http://$url' target='_blank'>$url</a>", $text2);
//      }
//    }
//  }

  //
//  dbg($text2);

  // Scan for referenced members:
  $n_members = preg_match_all("/(^|\s)\@([a-z0-9\_\-]+)\b/i", $text2, $matches);
  $members = array();
  if ($n_members) {
    foreach ($matches[2] as $name) {
      // Check if we have a member with this name:
      $user = user_load_by_name($name);
      if ($user) {
        $member = Member::create($user);
        $members[$member->uid()] = $member;
        $text2 = preg_replace("/(^|\s)(\@$name)\b/i", "$1" . $member->link(NULL), $text2);
      }
    }
  }

  // Scan for hash tags:
//  $n_members = preg_match_all("/(^|\s)\@([a-z0-9\_\-]+)\b/i", $text, $matches);

  $tags = array();
//  if ($n_members) {
//    $text2 = $text;
//    foreach ($matches[2] as $name) {
//      // Check if we have a member with this name:
//      $member = Member::create($name);
//      if ($member) {
//        $members[$member->uid()] = $member;
//        $text2 = preg_replace("/(^|\s)(\@$name)\b/i", "$1" . $member->link(NULL, TRUE), $text2);
//      }
//    }
//  }

  // Scan for entity links:
  $n_entities = preg_match_all("/\[([^\]]+)\]/", $text, $matches);
  $channels = array();
  if ($n_entities) {
    foreach ($matches[1] as $channel_title) {
      $channel = Channel::createByTitle($channel_title);
      if (!$channel) {
        break;
      }

      $channels[$channel->nid()] = $channel;
      $parent_entity_link = $channel->parentEntityLink();
      $text2 = str_replace("[$channel_title]", $parent_entity_link, $text2);
    }
  }

  // Insert break tags if requested:
  if ($nl2br) {
    $text2 = nl2br($text2);
  }

  return array(
    'filtered_text' => $text2,
    'members' => $members,
    'hash_tags' => $tags,
    'channels' => $channels,
  );
}

/**
 * Scans a piece of text (item or comment) for member references and hash tags, and converts these to links.
 *
 * @param $text
 */
function moonmars_text_filter($text, $nl2br = FALSE) {
  $scan = moonmars_text_scan($text, $nl2br);
  return $scan['filtered_text'];
}

/**
 * Scans a piece of text (item or comment) for member references and returns the Member objects.
 *
 * @param $text
 */
function moonmars_text_referenced_members($text) {
  $scan = moonmars_text_scan($text);
  return $scan['members'];
}

/**
 * Scans a piece of text (item or comment) for hash tags, and returns the Term objects.
 *
 * @param $text
 */
function moonmars_text_hash_tags($text) {
  $scan = moonmars_text_scan($text);
  return $scan['hash_tags'];
}

/**
 * Trims a bit of text to a maximum length, using ellipsis to indicate the trim.
 *
 * @param string $text
 * @param int $maxlen
 * @return string
 */
function moonmars_text_trim($text, $maxlen = 40) {
  return (strlen($text) <= $maxlen) ? $text : (substr($text, 0, $maxlen - 3) . '...');
}
