<?php

/**
 * Implements hook_menu().
 */
function moonmars_test_menu() {
  $items = array();
  $items['test/wants-nxn'] = array(
    'page callback'    => 'moonmars_test_wants_nxn',
    'access callback'  => 'user_is_superuser',
    'type'             => MENU_CALLBACK,
  );
  return $items;
}

function moonmars_test_wants_nxn() {
  $logged_in_member = Member::loggedInMember();
  $logged_in_member->load();

  $definitions = moonmars_nxn_definitions();

  foreach ($definitions as $nxn_category => $nxn_category_info) {
    foreach ($nxn_category_info['triumph types'] as $triumph_type => $triumph_type_info) {
      dbg("category = $nxn_category, type = $triumph_type");
      dbg($logged_in_member->nxnPref($nxn_category, $triumph_type));
      echo "<hr>";
    }
  }

}
