<?php

/**
 * Constant for specifying notifications of a certain type.
 */
const MOONMARS_NXN_NO   = 0;
const MOONMARS_NXN_YES  = 1;
const MOONMARS_NXN_SOME = 2;

/**
 * Implements hook_menu().
 */
function moonmars_nxn_menu() {
  $items = array();
  $items['user/%/notifications'] = array(
    'page callback'   => 'moonmars_nxn_list',
    'page arguments'  => array(1),
    'access callback' => 'user_is_logged_in',
    'type'            => MENU_CALLBACK,
  );
  $items['member/%/notifications/preferences'] = array(
    'page callback'   => 'drupal_get_form',
    'page arguments'  => array('moonmars_nxn_form', 1),
    'access callback' => 'user_is_logged_in',
    'type'            => MENU_CALLBACK,
  );
  $items['service/send-nxns'] = array(
    'page callback'   => 'moonmars_nxn_send_outstanding',
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_mail().
 */
function moonmars_nxn_mail($key, &$message, $params) {
  switch ($key) {
    case 'nxn':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['summary'];
      $message['body'][] = $params['message'];
      $message['body'][] = $params['unsubscribe'];
      $message['headers']['Content-Type'] = "text/html; charset='utf-8';";
      break;
  }
}

/**
 * Get the notification definitions.
 *
 * @return array
 */
function moonmars_nxn_definitions() {

  $new_member_conditions = array(
    'country' => array(
      'label'   => "Members from the same country as me",
      'default' => TRUE,
    ),
  );

  $new_group_conditions = array(
    'event'   => array(
      'label'   => "New events",
      'default' => TRUE,
    ),
    'project' => array(
      'label'   => "New projects",
      'default' => TRUE,
    ),
    'topic'   => array(
      'label'   => "Groups about a topic I'm interested in",
      'default' => TRUE,
    ),
  );

  $new_item_conditions = array(
    'mention' => array(
      'label'   => "Items that mention me",
      'default' => TRUE,
    ),
    'topic'   => array(
      'label'   => "Items about a topic I'm interested in",
      'default' => TRUE,
    ),
  );

  $new_comment_conditions = array(
    'mention' => array(
      'label'   => "Comments that mention me",
      'default' => TRUE,
    ),
    'item'    => array(
      'label'   => "Comments on an item I shared",
      'default' => TRUE,
    ),
    'comment' => array(
      'label'   => "Comments on an item I also commented on",
      'default' => TRUE,
    ),
    'topic'   => array(
      'label'   => "Comments about a topic I'm interested in",
      'default' => TRUE,
    ),
  );

  return array(
    'site'     => array(
      'title' => "Site",
      'description' => "Select your notification preferences for the whole site. This excludes closed groups that you aren't a member of.",
      'triumph types'  => array(
        'new-member'   => array(
          'title'       => 'New members',
          'description' => "Do you want to be notified about new members?",
          'default'     => MOONMARS_NXN_NO,
          'conditions'  => $new_member_conditions,
          'enabled'     => TRUE,
        ),
        'new-group'    => array(
          'title'       => 'New groups',
          'description' => "Do you want to be notified about new groups?",
          'default'     => MOONMARS_NXN_YES,
          'conditions'  => $new_group_conditions,
          'enabled'     => TRUE,
        ),
        'new-item'     => array(
          'title'       => 'New items',
          'description' => "Do you want to be notified about new items?",
          'default'     => MOONMARS_NXN_SOME,
          'conditions'  => $new_item_conditions,
          'enabled'     => TRUE,
        ),
        'new-comment'  => array(
          'title'       => 'New comments',
          'description' => "Do you want to be notified about new comments?",
          'default'     => MOONMARS_NXN_SOME,
          'conditions'  => $new_comment_conditions,
          'enabled'     => TRUE,
        ),
        'new-follower' => array(
          'title'       => 'New followers',
          'description' => "Do you want to be notified about new followers?",
          'default'     => MOONMARS_NXN_YES,
          'enabled'     => TRUE,
        ),
      ),
    ),
    'news' => array(
      'title' => "News",
      'description' => "Select your notification preferences for the News channel.",
      'triumph types'  => array(
        'new-item'     => array(
          'title'       => 'New items',
          'description' => "Do you want to be notified about new items?<br><strong>IT'S YOUR CHOICE BUT PLEASE LEAVE AS 'Yes' AS THIS IS HOW I NOTIFY EVERYONE ABOUT UPDATES TO THE SITE.</strong>",
          'default'     => MOONMARS_NXN_YES,
          'conditions'  => $new_item_conditions,
          'enabled'     => TRUE,
        ),
        'new-comment'  => array(
          'title'       => 'New comments',
          'description' => "Do you want to be notified about new comments?",
          'default'     => MOONMARS_NXN_SOME,
          'conditions'  => $new_comment_conditions,
          'enabled'     => TRUE,
        ),
      ),
    ),
    'channel'  => array(
      'title' => "My channel",
      'description' => "Select the notifications you want about your channel.",
      'triumph types'  => array(
        'new-item'    => array(
          'title'       => 'New items',
          'description' => "Do you want to be notified about new items shared in your channel?",
          'default'     => MOONMARS_NXN_YES,
          'conditions'  => $new_item_conditions,
          'enabled'     => TRUE,
        ),
        'new-comment' => array(
          'title'       => 'New comments',
          'description' => "Do you want to be notified about new comments posted in your channel?",
          'default'     => MOONMARS_NXN_YES,
          'conditions'  => $new_comment_conditions,
          'enabled'     => TRUE,
        ),
      ),
    ),
    'followee' => array(
      'title' => "My followees",
      'description' => "Select the notifications you want about the members you follow.",
      'triumph types'  => array(
        'new-item' => array(
          'title'       => 'New items',
          'description' => "Do you want to be notified when they share a new item?",
          'default'     => MOONMARS_NXN_YES,
          'conditions'  => $new_item_conditions,
          'enabled'     => TRUE,
        ),
        'new-comment' => array(
          'title'       => 'New comments',
          'description' => "Do you want to be notified when they post a new comment?",
          'default'     => MOONMARS_NXN_YES,
          'conditions'  => $new_comment_conditions,
          'enabled'     => TRUE,
        ),
        'new-page' => array(
          'title'       => 'New pages',
          'description' => "Do you want to be notified when they create a new page?",
          'default'     => MOONMARS_NXN_YES,
          'enabled'     => FALSE,
        ),
        'new-member' => array(
          'title'       => 'Joined group',
          'description' => "Do you want to be notified when they join a group?",
          'default'     => MOONMARS_NXN_YES,
          'enabled'     => TRUE,
        ),
        'update-member' => array(
          'title'       => 'Profile updated',
          'description' => "Do you want to be notified when they update their profile?",
          'default'     => MOONMARS_NXN_YES,
          'enabled'     => TRUE,
        ),
      ),
    ),
    'group'    => array(
      'title' => "My groups",
      'description' => "Select the notifications you want about your groups.",
      'triumph types'  => array(
        'new-member'        => array(
          'title'       => 'New members',
          'description' => "Do you want to be notified when someone joins?",
          'default'     => MOONMARS_NXN_YES,
          'conditions'  => $new_member_conditions,
          'enabled'     => TRUE,
        ),
        'new-group'         => array(
          'title'       => 'New subgroups',
          'description' => "Do you want to be notified when a new subgroup is created?",
          'default'     => MOONMARS_NXN_YES,
          'conditions'  => $new_group_conditions,
          'enabled'     => FALSE,
        ),
        'new-item'          => array(
          'title'       => 'New items',
          'description' => "Do you want to be notified when a new item is shared?",
          'default'     => MOONMARS_NXN_YES,
          'conditions'  => $new_item_conditions,
          'enabled'     => TRUE,
        ),
        'new-comment'       => array(
          'title'       => 'New comments',
          'description' => "Do you want to be notified when a new comment is posted?",
          'default'     => MOONMARS_NXN_YES,
          'conditions'  => $new_comment_conditions,
          'enabled'     => TRUE,
        ),
        'new-page'           => array(
          'title'       => 'New pages',
          'description' => "Do you want to be notified when a new page is created?",
          'default'     => MOONMARS_NXN_YES,
          'enabled'     => FALSE,
        ),
        'new-admin'         => array(
          'title'       => 'New administrator',
          'description' => "Do you want to be notified when the group gets a new adminstrator?",
          'default'     => MOONMARS_NXN_YES,
          'enabled'     => FALSE,
        ),
        'want-admin'        => array(
          'title'       => 'Administrator wanted',
          'description' => "Do you want to be notified when the groups needs a new adminstrator?",
          'default'     => MOONMARS_NXN_YES,
          'enabled'     => FALSE,
        ),
        'update-group'    => array(
          'title'       => 'Profile updated',
          'description' => "Do you want to be notified when the group profile is updated?",
          'default'     => MOONMARS_NXN_YES,
          'enabled'     => TRUE,
        ),
      ),
    ),
  );
}

/**
 * Get all the triumph types.
 *
 * @return array
 */
function moonmars_nxn_triumph_types() {
  static $triumph_types;

  if (isset($triumph_types)) {
    return $triumph_types;
  }

  $triumph_types = array();
  $definitions = moonmars_nxn_definitions();

  foreach ($definitions as $nxn_category_info) {
    foreach ($nxn_category_info['triumph types'] as $triumph_type => $nxn_info) {
      if (!in_array($triumph_type, $triumph_types)) {
        $triumph_types[] = $triumph_type;
      }
    }
  }

  return $triumph_types;
}

/**
 * List a member's notifications.
 *
 * @return string
 */
function moonmars_nxn_list($uid) {
  // Make sure the user is looking at their own notifications and not someone else's.
  $current_member = Member::currentMember();
  if ($current_member->uid() != $uid) {
    drupal_access_denied();
  }

  drupal_set_title('Your Notifications');

  $html = "
    <div id='notifications-form-buttons'>
      <a class='button' href='/" . $current_member->alias() . "/notifications/preferences'>Edit notifications preferences</a>
    </div>
  ";

  $html .= views_embed_view('notifications', 'page', $uid);

  return $html;
}

/**
 * Form for notifications preferences.
 *
 * @return array
 */
function moonmars_nxn_form($form, &$form_state, $uid) {
  // Make sure the user is looking at their own notifications and not someone else's.
  $current_member = Member::currentMember();
  $profile_member = Member::create($uid);
  if (!Member::equals($current_member, $profile_member)) {
    drupal_access_denied();
  }

  // Set the title:
  drupal_set_title("Edit notifications preferences");

  // Start building the form:
  $form = array(
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'moonmars_nxn') . '/js/nxn-form.js',
      ),
    ),
    'uid' => array(
      '#type'  => 'hidden',
      '#value' => $current_member->uid(),
    ),
    'entity_id' => array(
      '#type'  => 'hidden',
      '#value' => 0,
    ),
    'buttons' => array(
      '#markup' => "
        <p>These preferences are additive, which is to say, if one preference say 'yes', and another says 'no',
        the result will be 'yes'. For example, if you say you want no notifications about your groups, but you want all
        notifications about your followees, then if a followee posts something in one of your groups you'll be notified.</p>
        <p>The default settings should suit most people.</p>
        <div id='notifications-form-buttons'>
          <strong>Select:</strong>&nbsp;
          <input type='button' onclick='nxnSelectNone()' value='Nothing'>
          <input type='button' onclick='nxnSelectAll()' value='Everything'>
          <input type='button' onclick='nxnSelectDefault()' value='Default'>
        </div>
        <script>
        var nxnDefinitions = " . json_encode(moonmars_nxn_definitions()) . ";
        </script>
      ",
    ),
  );

  // Get the nxn definitions:
  $definitions = moonmars_nxn_definitions();

  foreach ($definitions as $nxn_category => $nxn_category_info) {
    // Create a fieldset for the category:
    $form[$nxn_category] = array(
      '#type'        => 'fieldset',
      '#title'       => $nxn_category_info['title'],
      '#description' => $nxn_category_info['description']
    );

    foreach ($nxn_category_info['triumph types'] as $triumph_type => $nxn_info) {
      if (!$nxn_info['enabled']) {
        continue;
      }

      $nxn_full_key = "nxn-$nxn_category-$triumph_type";
      $form[$nxn_category][$nxn_full_key] = array(
        '#type'          => 'radios',
        '#title'         => $nxn_info['title'],
        '#description'   => $nxn_info['description'],
        '#options'       => array(
          MOONMARS_NXN_NO  => 'No',
          MOONMARS_NXN_YES => 'Yes',
        ),
        '#default_value' => $current_member->nxnPrefWants($nxn_category, $triumph_type),
      );

      // If there are conditions...
      if (isset($nxn_info['conditions'])) {
        // Add the 'Some' option:
        $form[$nxn_category][$nxn_full_key]['#options'][MOONMARS_NXN_SOME] = 'Some';

        // Create the checkbox group:
        $nxn_cond_key = $nxn_full_key . '-cond';
        $form[$nxn_category][$nxn_cond_key] = array(
          '#type'          => 'checkboxes',
          '#title'         => 'Just notify me about:',
          '#default_value' => array_keys(array_filter($current_member->nxnPrefConditions($nxn_category, $triumph_type))),
        );

        // Add the options:
        foreach ($nxn_info['conditions'] as $nxn_condition => $nxn_condition_info) {
          $form[$nxn_category][$nxn_cond_key]['#options'][$nxn_condition] = $nxn_condition_info['label'];
        }
      }
    }
  }

  // Submit button:
  $form['submit'] = array(
    '#prefix' => "<div class='form-actions'>",
    '#type'   => 'submit',
    '#value'  => 'Save',
    '#submit' => array('moonmars_nxn_form_submit'),
    '#suffix' => "</div>",
  );

  return $form;
}

/**
 * Submit handler for nxn prefs form.
 */
function moonmars_nxn_form_submit($form, &$form_state) {
  // Get the member:
  $uid = (int) $form_state['values']['uid'];
  $member = Member::create($uid);

  // Get the entity_id:
  $entity_id = (int) $form_state['values']['entity_id'];

  // Remember the prefs:
  $nxn_prefs = array();

//  dpm($form_state['values']);

  foreach ($form_state['values'] as $key => $value) {
    $parts = explode('-', $key);

    if ($parts[0] != 'nxn') {
      continue;
    }

    $nxn_category = $parts[1];
    $triumph_type = "{$parts[2]}-{$parts[3]}";

    if (is_numeric($value)) {
      $nxn_prefs[$nxn_category][$triumph_type]['wants'] = (int) $value;
    }
    elseif (is_array($value) && $nxn_prefs[$nxn_category][$triumph_type]['wants'] == MOONMARS_NXN_SOME) {
      // Conditions array:
      $nxn_prefs[$nxn_category][$triumph_type]['conditions'] = serialize(array_map(function($x) {
        return (int) (bool) $x;
      }, $value));
    }
  }

  // Update database.
  // Delete all nxn prefs for this user:
  $q = db_delete('moonmars_nxn_pref')
    ->condition('uid', $member->uid());
  $q->execute();

//  dpm($nxn_prefs);

  // Insert new records for prefs:
  foreach ($nxn_prefs as $nxn_category => $triumph_types) {
    foreach ($triumph_types as $triumph_type => $nxn_pref) {
      $q = db_insert('moonmars_nxn_pref')
        ->fields(array(
          'uid'            => $member->uid(),
          'nxn_category'   => $nxn_category,
          'triumph_type'       => $triumph_type,
          'entity_id'      => $entity_id,
          'nxn_wants'      => $nxn_pref['wants'],
          'nxn_conditions' => isset($nxn_pref['conditions']) ? $nxn_pref['conditions'] : NULL,
        ));
      $q->execute();
    }
  }

  // Message:
  drupal_set_message("Your notifications preferences have been updated.");

  // Go back to their notifications:
//  $form_state['redirect'] = $member->alias() . '/notifications';
}

/**
 * Callback to create and send outstanding notifications.
 * Should be run virtually continuously.
 */
function moonmars_nxn_send_outstanding() {
  // Scan triumphs and create notifications:
  $n_created = Triumph::createOutstandingNxns();

  // Send outstanding notifications:
  $n_sent = Nxn::sendOutstanding();

  // Some info in watchdog:
  watchdog('moonmars_nxn', "Creating and sending outstanding nxns. $n_created nxns created. $n_sent nxns sent.");

  return NULL;
}
