<?php
// $Id$

/**
 * Class for nodes of type '<type>'.
 *
 * This class extends the class <base_class>, which is autogenerated
 * by the classes module.
 *
 * Do not edit the base class - edit this one. This class exists for you to add
 * your custom properties and methods, and will not be overwritten or deleted
 * (unless you do so manually).
 * 
 * You should always create objects of this class, not the base class.
 * Example:
 *   $x = <class>::create($nid);
 * and not:
 *   $x = <base_class>::create($nid);
 * 
 * @version <dt_generated>
 */
class x_class extends x_base_class {
  /*
   * Your stuff goes in here.
   */
}
