<?php
// $Id$

/**
 * Class stub for XEntity class.
 *
 * This class extends the XEntityBase class, which is autogenerated by the
 * classes module.
 *
 * Do not edit the base class - edit this one. This class exists for you to add
 * your custom properties and methods, and will not be overwritten.
 * 
 * You can make this a concrete (non-abstract) class by implementing the
 * abstract methods from XEntityBase.
 * 
 * @version <dt_generated>
 */
abstract class XEntity extends XEntityBase {
  /*
   * Your stuff goes in here.
   */
}
