<?php
/**
 * Makes some improvements to the Administration Menu provided by admin_menu, including:
 *   - Hides the default Add Content and Find Content links.
 *   - Hides the admin menu in the overlay.
 *   - Add content links for all content types
 *   - Find content links for all content types
 *   - Copies Configuration > People to People > Configuration
 *   - Removes duplicate items under Menus section
 *
 * @author Shaun Moss
 * @version 2011-08-28
 */

/**
 * Implements hook_init()
 */
function admin_menu_fix_init() {
  drupal_add_css(drupal_get_path('module', 'admin_menu_fix') . '/admin_menu_fix.css');
}

/**
 * Implements hook_menu().
 */
function admin_menu_fix_menu() {
  $items = array();
  $items['admin/content/find'] = array(
    'title' => 'Find content',
    'description' => 'Find and manage content, filtered by type.',
    'page callback' => 'admin_menu_fix_find_content',
    'page arguments' => array(3),
    'access arguments' => array('access content overview'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_admin_menu_output_alter().
 */
function admin_menu_fix_admin_menu_output_alter(&$content) {

  /*
    /////////////////////////////////////////////////////////
    // Create new submenu for 'Add Content':
    // Not needed now - this has since been added to admin_menu

    // Find the top-level menu item called "Content":
    $i = NULL;
    foreach ($content['menu'] as $key => $value) {
      if (is_array($value) && array_key_exists('#href', $value) && $value['#href'] == 'admin/content') {
        $i = $key;
        break;
      }
    }

    if ($i !== NULL) {
      $submenu = array();
      $content_submenu_added = FALSE;
      $j = 0;
      $types = _node_types_build()->names;
      foreach ($content['menu'][$i] as $key => $value) {

        if (is_numeric($key)) {

          if (!$content_submenu_added) {
            // Before we add the first numeric key, insert our 'Add content' menu at $j = 0
            $submenu[$j] = array(
              '#title' => t('Add content'),
              '#href' => 'node/add',
              '#options' => array('alias' => TRUE),
              '#weight' => $value['#weight'] - 1,
            );

            // Add the content types:
            $m = 0;
            foreach ($types as $type => $name) {
              $submenu[$j][$m] = array(
                '#title' => $name,
                '#href' => 'node/add/' . str_replace('_', '-', $type),
                '#options' => array('alias' => TRUE),
                '#weight' => $m,
              );
              $m++;
            }

            $j++;
            $content_submenu_added = TRUE;
          }

          // Add the submenu:
          $submenu[$j] = $value;
          $j++;
        }
        else {
          $submenu[$key] = $value;
        }
      }
      $content['menu'][$i] = $submenu;
  */

  /////////////////////////////////////////////////////////
  // Add "Find content" items:

  // Find the top-level menu item called "Content":
  $i = NULL;
  foreach ($content['menu'] as $key => $value) {
    if (is_array($value) && array_key_exists('#href', $value) && $value['#href'] == 'admin/content') {
      $i = $key;
      break;
    }
  }

  if (!$i !== NULL) {

    // Add a menu item "Find content":
    $j = count($content['menu'][$i]) - 1;
    $content['menu'][$i][$j] = array(
      '#title' => t('Find content'),
      '#href' => 'admin/content/node',
    );

    // Add submenu links for each content type:
    $types = _node_types_build()->names;
    foreach ($types as $type => $name) {
      $content['menu'][$i][$j][] = array(
        '#title' => $name,
        '#href' => 'admin/content/find/' . str_replace('_', '-', $type),
        '#options' => array('alias' => TRUE),
      );
    }

    // Set the order of the menu items:
    $n = 3;
    foreach ($content['menu'][$i] as &$item) {
      if (is_array($item) && isset($item['#href'])) {
        if ($item['#href'] == 'node/add') {
          $item['#weight'] = 1;
        }
        elseif ($item['#href'] == 'admin/content/node') {
          $item['#weight'] = 2;
        }
        else {
          $item['#weight'] = $n++;
        }
      }
    }
  }

/*
  /////////////////////////////////////////////////////////
  // Fix duplicate "Menu" menu items:
  // This seems to have been fixed as well.

  // Find the top-level menu item called "Content":
  $i = NULL;
  foreach ($content['menu'] as $key => $value) {
    if (is_array($value) && array_key_exists('#href', $value) && $value['#href'] == 'admin/structure') {
      $i = $key;
      break;
    }
  }
  
  if ($i !== NULL) {
    
    // Find the "Menu" section:
    $j = NULL;
    foreach ($content['menu'][$i] as $key => $value) {
      if (is_array($value) && array_key_exists('#href', $value) && $value['#href'] == 'admin/structure/menu') {
        $j = $key;
        break;
      }
    }
    
    if ($j !== NULL) {
      // Strip out the superfluous menu entries:
      $submenu = array();
      foreach ($content['menu'][$i][$j] as $key => $value) {
        if (!(is_numeric($key) && is_array($value) && array_key_exists($value['#href'], $content['menu'][$i][$j]))) {
          $submenu[$key] = $value;
        }
      }
      
      if (!empty($submenu)) {
        $content['menu'][$i][$j] = $submenu;
      }
    }
  }
*/

  /////////////////////////////////////////////////////////
  // Copy "Configuration > People" to "People > Configuration":

  // Find the top-level menu item called "Configuration":
  $i = NULL;
  foreach ($content['menu'] as $key => $value) {
    if (is_array($value) && array_key_exists('#href', $value) && $value['#href'] == 'admin/config') {
      $i = $key;
      break;
    }
  }

  if ($i !== NULL) {
    // Find the "People" item within the "Configuration" section:
    $j = NULL;
    foreach ($content['menu'][$i] as $key => $value) {
      if (is_array($value) && array_key_exists('#href', $value) && $value['#href'] == 'admin/config/people') {
        $j = $key;
        break;
      }
    }

    if ($j !== NULL) {
      // Find the top-level menu item called "People":
      $k = NULL;
      foreach ($content['menu'] as $key => $value) {
        if (is_array($value) && array_key_exists('#href', $value) && $value['#href'] == 'admin/people') {
          $k = $key;
          break;
        }
      }

      // Copy the submenu:
      if ($k !== NULL) {
        $submenu = $content['menu'][$i][$j];
        $submenu['#title'] = t('Configuration');
        $content['menu'][$k][] = $submenu;
      }
    }
  }

/*
  /////////////////////////////////////////////////////////
  // Move 'Dashboard', 'Tasks', 'Help' and 'Advanced Help' under the 'Index' menu.
Tasks is gone and Index is now hidden under the favicon, so we don't really need this now.

  // Find the top-level menu item called "Index":
  $i = NULL;
  foreach ($content['menu'] as $key => $value) {
    if (is_array($value) && array_key_exists('#href', $value) && $value['#href'] == 'admin/index') {
      $i = $key;
      break;
    }
  }

  if ($i !== NULL) {
    // We want to add these in order, so let's do a loop:
    $paths = array('admin/dashboard', 'admin/tasks', 'admin/help', 'admin/advanced_help');
    foreach ($paths as $path) {
      // Look for this path in the top-level menu:
      foreach ($content['menu'] as $key => $value) {
        if (is_array($value) && array_key_exists('#href', $value) && $value['#href'] == $path) {
          $content['menu'][$i][] = $value;
          unset($content['menu'][$key]);
        }
      }
    }
  }
*/

  /////////////////////////////////////////////////////////
  // Move 'Advanced Help' under 'Help'.

  // Find the top-level menu item called "Help":
  $i = NULL;
  foreach ($content['menu'] as $key => $value) {
    if (is_array($value) && array_key_exists('#href', $value) && $value['#href'] == 'admin/help') {
      $i = $key;
      break;
    }
  }

  if ($i !== NULL) {
    // Look for the Advanced Menu in the top-level menu:
    foreach ($content['menu'] as $key => $value) {
      if (is_array($value) && array_key_exists('#href', $value) && $value['#href'] == 'admin/advanced_help') {
        $content['menu'][$i][] = $value;
        unset($content['menu'][$key]);
      }
    }
  }
}

/**
 * Show the "Find content" page, with the content type filter set or reset.
 *
 * @param string $type
 * @return string The HTML
 */
function admin_menu_fix_find_content($type) {
  // Update the filter parameters in the session:
  if ($type) {
    $_SESSION['node_overview_filter'] = array(
      0 => array(
        0 => 'type',
        1 => str_replace('-', '_', $type),
      ),
    );
  }
  else {
    $_SESSION['node_overview_filter'] = array();
  }

  // Go to the normal Content page:
  drupal_goto('admin/content/node');
}
