<?php
/**
 * User: shaun
 * Date: 2012-09-08
 * Time: 6:24 AM
 *
 * An actor in moonmars.com is a special kind of entity. These each have a class.
 * This module contains functions that apply to more than one entity type.
 * Current actor classes:
 *   Member (extends User)
 *   Group (extends Node)
 *   Item (extends Node)
 *   ItemComment (extends Comment)
 *   MoonMarsRelation (extends Relation)
 */

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Constants

/**
 * Define the minimum length for an actor code (i.e. username of group tag).
 * I'm using 3 here to prevent meaningless tags, but could be changed to 2 or 1. There's not really any reason not to.
 *
 * @var int
 */
const MOONMARS_ACTOR_CODE_MIN_LENGTH = 3;

/**
 * Define the maximum length for an actor code (i.e. username of group tag).
 * Since usernames are actor codes, we'll just use the Drupal default max length which is USERNAME_MAX_LENGTH (60).
 *
 * @var int
 */
const MOONMARS_ACTOR_CODE_MAX_LENGTH = USERNAME_MAX_LENGTH;

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Core hooks

/**
 * Implements hook_menu().
 */
function moonmars_actors_menu() {
  $items = array();
  $items['ajax/check-actor-code'] = array(
    'page callback'   => 'moonmars_actors_ajax_check_code',
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
  );
  return $items;
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Checking member and group codes

/**
 * AJAX callback to check if a actor code is valid.
 */
function moonmars_actors_ajax_check_code() {
  // Get parameters from the query string:
  $actor_type = isset($_REQUEST['actorType']) ? $_REQUEST['actorType'] : NULL;
  $actor_code = isset($_REQUEST['actorCode']) ? $_REQUEST['actorCode'] : NULL;
  $actor_id = isset($_REQUEST['actorId']) ? $_REQUEST['actorId'] : NULL;

  // Default result:
  $data = array(
    'result' => FALSE,
  );

  // Check for valid parameters:
  if (!$actor_type || !in_array($actor_type, array('member', 'group')) || !$actor_code) {
    $data['message'] = "Invalid parameters";
    echo json_encode($data);
    return;
  }

  // Check for valid characters and and length:
  if (!moonmars_actors_valid_code($actor_code)) {
    $data['message'] = "Invalid";
    echo json_encode($data);
    return;
  }

  // Check if any other actor of the same type has this code:
  if ($actor_type == 'member') {
    // Check if any other member has the same username:
    $q = db_select('users', 'u')
      ->fields('u', array('uid'))
      ->condition('name', $actor_code);
    // If editing a member, look for a different member with the same username:
    if ($actor_id) {
      $q->condition('uid', $actor_id, '!=');
    }
  }
  elseif ($actor_type == 'group') {
    // Check if any other group has the same tag:
    $q = db_select('node', 'n')
      ->fields('n', array('nid'));
    $q->join('field_data_field_group_tag', 'gt', "n.nid = gt.entity_id");
    $q->condition('field_group_tag_value', $actor_code);
    // If editing a group, look for a different group with the same tag:
    if ($actor_id) {
      $q->condition('nid', $actor_id, '!=');
    }
  }

  // Check if a match was found:
  if ($q->execute()->rowCount()) {
    $data['message'] = "Taken";
    echo json_encode($data);
    return;
  }

  // It's ok:
  $data = array(
    'result' => TRUE,
    'message' => "OK",
  );
  echo json_encode($data);
  return;
}

/**
 * Check if a member name or group tag is valid.
 *
 * This means:
 *   - Between 3 and 60 (USERNAME_MAX_LENGTH) characters.
 *   - Letters, digits, hyphens and underscores only.
 *
 * This set of rules permits:
 *   - Drupal will allow it. @see user.module/user_validate_name()
 *   - Apache will allow it. If a username starts with a period then Apache will show a Forbidden message if their
 *       profile path is requested.
 *   - Uses only unreserved characters.
 *       @see http://www.456bereastreet.com/archive/201006/be_careful_with_non-ascii_characters_in_urls/
 *   - Member profile alias will match the username exactly, i.e. /member/$username
 *   - Group profile alias will match the group tag exactly, i.e. /group/$group_tag
 *
 * @param $name
 * @return bool
 */
function moonmars_actors_valid_code($name) {
  return (bool) preg_match("/^[a-z0-9\-\_]{" . MOONMARS_ACTOR_CODE_MIN_LENGTH . "," . MOONMARS_ACTOR_CODE_MAX_LENGTH . "}$/i", $name);
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Functions and hooks for saving members and groups

/**
 * Common code for resetting aliases when saving members and groups.
 *
 * @param EntityBase $actor
 */
function moonmars_actors_reset_aliases($actor) {
  // Update the alias for the actor:
  $actor->resetAlias();

  // Update the alias and title for the actor's channel:
  $channel = $actor->channel();
  $channel->resetAliasAndTitle();
}

/**
 * Implements hook_entity_insert().
 *
 * Note, we use this hook instead of hook_node_insert() as it gets called later in the cycle, after
 * pathauto_node_insert_alias() sets the alias according to the pattern. hook_node_insert() is called before.
 */
function moonmars_actors_entity_insert($entity, $entity_type) {
  // Check if it's a member or group:
  if ($entity_type == 'user' || ($entity_type == 'node' && $entity->type == 'group')) {

    // Get the actor:
    $actor = moonmars_actors_get_actor($entity_type, $entity);

    // Create triumphs:
    if ($actor instanceof Member) {
      Triumph::newMember($actor);
    }
    elseif ($actor instanceof Group) {
      Triumph::newGroup($actor);
    }

    // Update the actor alias and channel alias and title:
    moonmars_actors_reset_aliases($actor);
  }
}

/**
 * Implements hook_entity_update().
 *
 * Note, we use this hook instead of hook_node_update() as it gets called later in the cycle, after
 * pathauto_node_update_alias() sets the alias according to the pattern. hook_node_update() is called before.
 */
function moonmars_actors_entity_update($entity, $entity_type) {
  // Check if it's a member or group:
  if ($entity_type == 'user' || ($entity_type == 'node' && $entity->type == 'group')) {

    // Get the actor:
    $actor = moonmars_actors_get_actor($entity_type, $entity);

    // Create triumphs:
    $current_member = Member::currentMember();
    if ($actor instanceof Member) {
      Triumph::updateMember($actor, $current_member);
    }
    elseif ($actor instanceof Group) {
      Triumph::updateGroup($actor, $current_member);
    }

    // Update the actor alias and channel alias and title:
    moonmars_actors_reset_aliases($actor);
  }
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Functions for getting and creating actor entities and channels

/**
 * Gets an EntityBase-derived object from a Drupal entity.
 *
 * @static
 * @param string $entity_type
 * @param object|int $entity
 * @return EntityBase
 *   EntityBase-derived class, e.g. Member, Group, Item, ItemComment, MoonMarsRelation, etc.
 */
function moonmars_actors_get_actor($entity_type, $entity) {
  switch ($entity_type) {
    case 'user':
      return Member::create($entity);

    case 'node':
      // Get the node type:
      $node_type = is_uint($entity) ? node_get_type($entity) : $entity->type;

      // Get the node class:
      $class = ucfirst($node_type);

      // If the node class exists, instantiate:
      if (class_exists($class)) {
        // Note I create the object using $entity instead of reloading the node (which would be another way of getting
        // the type), to prevent the node we just loaded from clobbering the one we have in memory.
        // My caching mechanism is better than Drupal's, unfortunately.
        return $class::create($entity);
      }

      // Fall back to base Node class:
      return Node::create($entity);

    case 'comment':
      // Get the cid:
      $cid = is_uint($entity) ? $entity : $entity->cid;

      // Get the comment's node type.
      $node_type = comment_get_node_type($cid);

      // Get the comment class:
      $class = ucfirst($node_type) . 'Comment';

      // If the comment class exists, instantiate.
      // This will capture ItemComment and potential other future comment classes such as ArticleComment or BlogPostComment.
      if (class_exists($class)) {
        return $class::create($entity);
      }

      // Fall back to base Comment class:
      return Comment::create($entity);

    case 'relation':
      // Create the object:
      return MoonMarsRelation::create($entity);
  }

  return FALSE;
}

/**
 * Get the entity with current focus from the URL.
 *
 * @static
 * @return bool
 */
function moonmars_actors_get_actor_from_url() {
  $valid_entity_types = array(
    'user',
    'node',
    'comment',
    'relation'
  );

  // Look for the entity type and id in the request_uri:
  $uri = trim($_SERVER['REQUEST_URI'], '/');

  // If we're at 'user' then the entity is the current logged-in user:
  if ($uri == 'user' && user_is_logged_in()) {
    return Member::currentMember();
  }

  // Check for a normal user/%uid or node/%nid type of path:
  $parts = explode('/', $uri);
  if (count($parts) >= 2 && in_array($parts[0], $valid_entity_types) && is_uint($parts[1])) {
    return moonmars_actors_get_actor($parts[0], $parts[1]);
  }

  // Maybe it's an alias. Try converting to normal path from just the first 2 path parts.
  $entity_alias = $parts[0] . (isset($parts[1]) ? ('/' . $parts[1]) : '');
  $path = drupal_get_normal_path($entity_alias);

  // Check again:
  $parts = explode('/', $path);
  if (count($parts) >= 2 && in_array($parts[0], $valid_entity_types) && is_uint($parts[1])) {
    return moonmars_actors_get_actor($parts[0], $parts[1]);
  }

  // Not an entity path:
  return FALSE;
}

/**
 * Creates a new channel for an entity.
 *
 * @param EntityBase $entity
 * @return int
 */
function moonmars_actors_create_channel(EntityBase $entity) {
  // Create the new channel:
  $channel = Channel::create()
    ->setProperties(array(
                         'uid'   => $entity->uid(),
                         'title' => $entity->channelTitle(),
                    ));

  // Save the node for the first time, which will give it a nid, which we need to create the relationship:
  $channel->save();

  // Create the relationship between the entity and the relationship:
  MoonMarsRelation::createNewBinary('has_channel', $entity, $channel);

  // Reset the channel's alias and title. This needs to be done after creating the relationship.
  $channel->resetAliasAndTitle();

  // Return the Channel:
  return $channel;
}

/**
 * Get an entity's channel.
 *
 * @param EntityBase $entity
 * @param bool $create
 * @return int
 */
function moonmars_actors_get_channel(EntityBase $entity, $create = TRUE) {
  // Check if the entity already has a channel:
  $rels = MoonMarsRelation::searchBinary('has_channel', $entity, NULL);

  if (!empty($rels)) {
    return $rels[0]->endpoint(1);
  }

  // If the entity has no channel, and $create is TRUE, create the channel now:
  if ($create) {
    return moonmars_actors_create_channel($entity);
  }

  return NULL;
}
